# These are supported funding model platforms

# GitHub Sponsors (organization)
github: FreeForCharity

# Custom funding links (displayed in addition to GitHub Sponsors)
custom:
  - 'https://ffcworkingsite1.org'
  - 'https://ffcworkingsite1.org/#donate'
