/**
 * Guards the self-hosted font setup in src/lib/fonts.ts.
 *
 * next/font options must be literals, so fonts.ts repeats values that are
 * generated by scripts/fonts/build_local_fonts.py and recorded in
 * src/fonts/manifest.json. These tests parse fonts.ts as text (next/font
 * calls are compiled away by SWC and cannot be executed under Jest) and fail
 * if the two drift apart, a file goes missing, or an *Ext face stops joining
 * its base family.
 */
import { createHash } from 'crypto'
import fs from 'fs'
import path from 'path'

const ROOT = path.join(__dirname, '..', '..')
const FONTS_TS = path.join(ROOT, 'src', 'lib', 'fonts.ts')
const FONTS_DIR = path.join(ROOT, 'src', 'fonts')

interface ManifestFile {
  subset: 'latin' | 'ext'
  sha256: string
  bytes: number
  unicode_range: string
}

interface Manifest {
  families: Record<string, { folder: string; files: Record<string, ManifestFile> }>
}

interface FontCall {
  name: string
  body: string
  paths: string[]
  unicodeRange: string | undefined
  fontFamily: string | undefined
}

const source = fs.readFileSync(FONTS_TS, 'utf8')
const manifest: Manifest = JSON.parse(
  fs.readFileSync(path.join(FONTS_DIR, 'manifest.json'), 'utf8')
)

const manifestFiles = new Map<string, ManifestFile & { dir: string }>()
for (const family of Object.values(manifest.families)) {
  for (const [file, meta] of Object.entries(family.files)) {
    manifestFiles.set(file, { ...meta, dir: path.join(ROOT, family.folder) })
  }
}

function parseCalls(): FontCall[] {
  const calls: FontCall[] = []
  const re = /export const (\w+) = localFont\(\{([\s\S]*?)\n\}\)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(source)) !== null) {
    const body = m[2]
    calls.push({
      name: m[1],
      body,
      paths: [...body.matchAll(/path: '([^']+)'/g)].map((p) => p[1]),
      unicodeRange: /prop: 'unicode-range',\s*value:\s*'([^']+)'/.exec(body)?.[1],
      fontFamily: /prop: 'font-family', value: "'([^']+)'"/.exec(body)?.[1],
    })
  }
  return calls
}

const calls = parseCalls()
const byName = new Map(calls.map((c) => [c.name, c]))
const baseCalls = calls.filter((c) => !c.name.endsWith('Ext'))
const extCalls = calls.filter((c) => c.name.endsWith('Ext'))

describe('self-hosted fonts (src/lib/fonts.ts)', () => {
  it('does not download fonts from Google at build time', () => {
    expect(source).not.toMatch(/next\/font\/google/)
    expect(source).toMatch(/from 'next\/font\/local'/)
  })

  it('declares a latin and an ext call for every family in the manifest', () => {
    expect(baseCalls).toHaveLength(Object.keys(manifest.families).length)
    expect(extCalls).toHaveLength(baseCalls.length)
    for (const base of baseCalls) {
      expect(byName.has(`${base.name}Ext`)).toBe(true)
    }
  })

  it.each(calls.map((c) => [c.name, c] as const))(
    '%s references committed font files that match the manifest',
    (_name, call) => {
      expect(call.paths.length).toBeGreaterThan(0)
      const expectedSubset = call.name.endsWith('Ext') ? 'ext' : 'latin'
      for (const rel of call.paths) {
        const abs = path.resolve(path.dirname(FONTS_TS), rel)
        expect(fs.existsSync(abs)).toBe(true)
        const meta = manifestFiles.get(path.basename(abs))
        expect(meta).toBeDefined()
        expect(meta!.subset).toBe(expectedSubset)
        expect(path.dirname(abs)).toBe(meta!.dir)
        expect(call.unicodeRange).toBe(meta!.unicode_range)
      }
    }
  )

  it.each(extCalls.map((c) => [c.name, c] as const))(
    '%s joins its base family and is loaded only on demand',
    (name, call) => {
      const baseName = name.replace(/Ext$/, '')
      // next/font names a family after the JS constant, so the Ext faces
      // must declare exactly that name to merge into the same family.
      expect(call.fontFamily).toBe(baseName)
      expect(call.body).toMatch(/preload: false/)
      expect(call.body).toMatch(/adjustFontFallback: false/)
    }
  )

  it.each(baseCalls.map((c) => [c.name, c] as const))(
    '%s is preloaded with a metric-matched fallback and no custom family',
    (_name, call) => {
      expect(call.fontFamily).toBeUndefined()
      expect(call.body).not.toMatch(/preload: false/)
      expect(call.body).toMatch(/adjustFontFallback: '(Arial|Times New Roman)'/)
    }
  )

  it('applies every Ext class alongside its base class', () => {
    const lists = [
      ...source.matchAll(/export const (\w+FontVariables) = \[([\s\S]*?)\]\.join/g),
    ].map((m) => ({ name: m[1], items: [...m[2].matchAll(/(\w+)\.variable/g)].map((v) => v[1]) }))
    expect(lists.map((l) => l.name).sort()).toEqual([
      'presentationFontVariables',
      'siteFontVariables',
    ])
    const used = lists.flatMap((l) => l.items)
    for (const base of baseCalls) {
      expect(used).toContain(base.name)
      expect(used).toContain(`${base.name}Ext`)
    }
    for (const list of lists) {
      for (const item of list.items) {
        const partner = item.endsWith('Ext') ? item.replace(/Ext$/, '') : `${item}Ext`
        expect(list.items).toContain(partner)
      }
    }
  })
})

describe('committed font files (src/fonts)', () => {
  it.each([...manifestFiles.entries()])('%s matches its manifest checksum', (file, meta) => {
    const buf = fs.readFileSync(path.join(meta.dir, file))
    expect(buf.length).toBe(meta.bytes)
    expect(createHash('sha256').update(buf).digest('hex')).toBe(meta.sha256)
  })

  it.each(Object.values(manifest.families).map((f) => [f.folder] as const))(
    '%s ships its SIL Open Font License',
    (folder) => {
      const license = fs.readFileSync(path.join(ROOT, folder, 'OFL.txt'), 'utf8')
      expect(license).toMatch(/SIL OPEN FONT LICENSE/i)
    }
  )
})
