"""Bundle the Minitab + SPSS cross-verification artifacts into a single
shareable zip.

Output:
    scripts/cross-platform-verification/tabs_v2_cross_platform_verification.zip

Contents (relative paths inside the zip):
    README.md                                  - top-level overview
    minitab/tabs_v2_crp200_minitab.csv         - Minitab worksheet
    minitab/tabs_v2_validation.MTB             - Minitab Exec macro
    minitab/README.md                          - Minitab workflow
    spss/tabs_v2_crp200_spss.sav               - SPSS native data
    spss/tabs_v2_crp200_spss.csv               - same data, CSV form
    spss/tabs_v2_validation.sps                - SPSS syntax (Run -> All)
    spss/README.md                             - SPSS workflow

Usage:
    python scripts/cross-platform-verification/build_zip.py
"""
from __future__ import annotations

import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_ZIP = Path(__file__).resolve().parent / "tabs_v2_cross_platform_verification.zip"

MANIFEST = [
    # (source path relative to repo root, destination path inside zip)
    ("scripts/minitab/tabs_v2_crp200_minitab.csv", "minitab/tabs_v2_crp200_minitab.csv"),
    ("scripts/minitab/tabs_v2_validation.MTB", "minitab/tabs_v2_validation.MTB"),
    ("scripts/minitab/README.md", "minitab/README.md"),
    ("scripts/spss/tabs_v2_crp200_spss.sav", "spss/tabs_v2_crp200_spss.sav"),
    ("scripts/spss/tabs_v2_crp200_spss.csv", "spss/tabs_v2_crp200_spss.csv"),
    ("scripts/spss/tabs_v2_validation.sps", "spss/tabs_v2_validation.sps"),
    ("scripts/spss/README.md", "spss/README.md"),
]

TOP_README = """# TABS V2 Cross-Platform Verification Bundle

This zip bundles everything a Minitab or SPSS user needs to independently
reproduce the descriptive + reliability layer of the TABS validation
pipeline on the same frozen N=200 dataset (`public/datasets/TABS_V2_CRP_2026_public_dataset.csv`)
that drives the Python and R analyses.

The CFA-derived statistics (McDonald's omega from CFA, composite reliability
with proper SEs, AVE, HTMT, HTMT2, bifactor decompositions, second-order CFA,
multigroup CFA, measurement invariance, ESEM, IRT GRM, Mardia normality)
require an SEM package (lavaan in R, semopy in Python, AMOS, or Mplus); none
of the platforms in this bundle support those natively. The Python pipeline +
R verification script in the source repo are the authoritative source for
those statistics.

## Quick start - SPSS (about 2 clicks once SPSS is open)

1. Unzip this archive into any folder.
2. Open `spss/tabs_v2_validation.sps` in SPSS (`File -> Open -> Syntax`).
3. `Run -> All`. Output appears in a new Viewer document.

The SPSS syntax targets the IBM SPSS Statistics 31.0 license that includes
Statistics Base, Regression, Bootstrapping, Missing Values, and Advanced
Statistics. It uses the Bootstrapping module for proper Cronbach alpha CIs
and Missing Values for Little's MCAR test - both 1:1 with the Python
pipeline.

## Quick start - Minitab (about 3 clicks once Minitab is open)

1. Unzip this archive into any folder.
2. `File -> Open Worksheet -> minitab/tabs_v2_crp200_minitab.csv`
3. `File -> Run an Exec -> minitab/tabs_v2_validation.MTB -> Run 1 time`

KMO and Bartlett's sphericity are GUI-only options on the Factor Analysis
dialog in Minitab (no session subcommand). To see them, run the Factor
Analysis block manually from the menu and check the boxes in `Options...`.

## What's in the zip

```
README.md                                <- you are reading this
minitab/
  README.md                              <- Minitab-specific workflow + expected values
  tabs_v2_crp200_minitab.csv             <- pre-encoded numeric data, short item names
  tabs_v2_validation.MTB                 <- Minitab Exec macro
spss/
  README.md                              <- SPSS-specific workflow + expected values
  tabs_v2_crp200_spss.sav                <- SPSS native binary data file
  tabs_v2_crp200_spss.csv                <- same data, CSV form
  tabs_v2_validation.sps                 <- SPSS syntax file (Run -> All)
```

## Three quick spot-checks that should match exactly

| Stat | Expected | Should match |
|---|---|---|
| Cronbach's alpha (Barriers, 18 items) | 0.873 | Python `cronbach_alpha`, R `psych::alpha` |
| Cronbach's alpha (Readiness, 17 items) | 0.917 | same |
| Cronbach's alpha (Maturity, 8 items) | 0.885 | same |
| Listwise N (Barriers / Readiness / Maturity) | 192 / 181 / 191 | same |
| KMO (Barriers / Readiness / Maturity) | 0.851 / 0.927 / 0.912 | R `psych::KMO` |
| Bartlett chi-squared (Barriers) | 1135.51 | R `psych::cortest.bartlett` |

If any of these disagree with the Python output, the data import is off
(usually missing-value coding); resolve before interpreting anything else.

## Where this bundle came from

Generated by `scripts/cross-platform-verification/build_zip.py` in the
TABS V2 source repository. Re-run that script to regenerate this bundle
after the source dataset or analysis pipeline changes.
"""


def main() -> None:
    missing: list[str] = []
    for src_rel, _ in MANIFEST:
        src = REPO_ROOT / src_rel
        if not src.exists():
            missing.append(src_rel)
    if missing:
        raise SystemExit(
            "Missing required artifacts (run build_minitab_csv.py and "
            "build_spss_artifacts.py first):\n  " + "\n  ".join(missing)
        )

    with zipfile.ZipFile(OUT_ZIP, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        # Top-level README
        zf.writestr("README.md", TOP_README)

        for src_rel, dest in MANIFEST:
            src = REPO_ROOT / src_rel
            zf.write(src, arcname=dest)

    size_kb = OUT_ZIP.stat().st_size / 1024
    print(f"Wrote {OUT_ZIP} ({size_kb:,.1f} KB)")
    print()
    print("Contents:")
    with zipfile.ZipFile(OUT_ZIP) as zf:
        for info in zf.infolist():
            print(f"  {info.filename:50s}  {info.file_size:>10,} bytes")


if __name__ == "__main__":
    main()
