import nodemailer from 'nodemailer'
import fs from 'fs'
import path from 'path'

async function sendEmail() {
  try {
    const reportPath = path.join(process.cwd(), 'reports')
    const files = fs.readdirSync(reportPath)
    // Get the most recent report file
    const latestReport = files
      .filter((f) => f.startsWith('ga-report-') && f.endsWith('.json'))
      .sort()
      .pop()

    if (!latestReport) {
      console.error('No report file found to send.')
      return
    }

    const reportContent = JSON.parse(fs.readFileSync(path.join(reportPath, latestReport), 'utf-8'))
    const totals = reportContent.totals?.[0]?.metricValues || []

    // Extract key metrics (safe access)
    const activeUsers = totals[0]?.value || '0'
    const newUsers = totals[1]?.value || '0'
    const sessions = totals[2]?.value || '0'
    const views = totals[4]?.value || '0'

    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.office365.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    })

    const mailOptions = {
      from: process.env.SMTP_FROM || process.env.SMTP_USER,
      to: process.env.REPORT_RECIPIENT_EMAIL || 'clarke@technologyadoptionbarriers.org',
      subject: `📊 TABS Weekly Analytics Report - ${new Date().toISOString().split('T')[0]}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h2>TABS Website Analytics (Last 28 Days)</h2>
          <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
            <tr style="background-color: #f2f2f2;">
              <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Metric</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Count</th>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">Active Users</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${activeUsers}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">New Users</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${newUsers}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">Page Views</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${views}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">Sessions</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${sessions}</td>
            </tr>
          </table>
          <p style="margin-top: 20px; color: #666; font-size: 12px;">
            This is an automated report generated by the TABS GitHub Actions workflow.
          </p>
        </div>
      `,
    }

    if (!process.env.SMTP_PASS) {
      console.warn('SMTP_PASS not set. Skipping email send (dry run).')
      console.log('Would have sent email to:', mailOptions.to)
      return
    }

    await transporter.sendMail(mailOptions)
    console.log('Email sent successfully!')
  } catch (error) {
    console.error('Error sending email:', error)
    process.exit(1)
  }
}

sendEmail()
