import nodemailer from 'nodemailer'
import fs from 'fs'
import path from 'path'

export interface ReportMetrics {
  activeUsers: string
  newUsers: string
  sessions: string
  views: string
}

/**
 * Extract the key GA metrics from a generated ga-report-*.json payload.
 * Defensive: every field falls back to '0' so a partial report never throws.
 */
export function extractMetrics(reportContent: unknown): ReportMetrics {
  const totals =
    (reportContent as { totals?: Array<{ metricValues?: Array<{ value?: string }> }> })?.totals?.[0]
      ?.metricValues || []
  return {
    activeUsers: totals[0]?.value || '0',
    newUsers: totals[1]?.value || '0',
    sessions: totals[2]?.value || '0',
    views: totals[4]?.value || '0',
  }
}

/** Build the HTML body for the weekly analytics email. */
export function buildReportHtml(metrics: ReportMetrics): string {
  return `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h2>TABS Website Analytics (Last 28 Days)</h2>
          <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
            <tr style="background-color: #f2f2f2;">
              <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Metric</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Count</th>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">Active Users</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${metrics.activeUsers}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">New Users</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${metrics.newUsers}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">Page Views</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${metrics.views}</td>
            </tr>
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">Sessions</td>
              <td style="padding: 10px; border: 1px solid #ddd;">${metrics.sessions}</td>
            </tr>
          </table>
          <p style="margin-top: 20px; color: #666; font-size: 12px;">
            This is an automated report generated by the TABS GitHub Actions workflow.
          </p>
        </div>
      `
}

export interface BuildMailOptionsArgs {
  reportContent: unknown
  from: string
  to: string
  /** ISO date (YYYY-MM-DD); defaults to today. Injectable for deterministic tests. */
  date?: string
}

/** Build the nodemailer message object from a GA report payload. Pure + testable. */
export function buildMailOptions({ reportContent, from, to, date }: BuildMailOptionsArgs) {
  const day = date || new Date().toISOString().split('T')[0]
  return {
    from,
    to,
    subject: `📊 TABS Weekly Analytics Report - ${day}`,
    html: buildReportHtml(extractMetrics(reportContent)),
  }
}

async function sendEmail() {
  try {
    const reportPath = path.join(process.cwd(), 'reports')
    const files = fs.readdirSync(reportPath)
    // Get the most recent report file
    const latestReport = files
      .filter((f) => f.startsWith('ga-report-') && f.endsWith('.json'))
      .sort()
      .pop()

    if (!latestReport) {
      console.error('No report file found to send.')
      return
    }

    const reportContent = JSON.parse(fs.readFileSync(path.join(reportPath, latestReport), 'utf-8'))

    const mailOptions = buildMailOptions({
      reportContent,
      from: process.env.GOOGLE_PROJECT_OWNER_EMAIL || '',
      to: process.env.REPORT_RECIPIENT_EMAIL || 'clarke@technologyadoptionbarriers.org',
    })

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GOOGLE_PROJECT_OWNER_EMAIL,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    })

    if (!process.env.GMAIL_APP_PASSWORD) {
      console.warn('GMAIL_APP_PASSWORD not set. Skipping email send (dry run).')
      console.log('Would have sent email to:', mailOptions.to)
      return
    }

    await transporter.sendMail(mailOptions)
    console.log('Email sent successfully!')
  } catch (error) {
    console.error('Error sending email:', error)
    process.exit(1)
  }
}

// ESM-safe entrypoint guard (tsx uses CJS for .ts files; typeof check prevents
// ReferenceError if the module is ever loaded in a pure-ESM context). Keeps the
// pure builders above importable from tests without triggering a real send.
if (typeof require !== 'undefined' && require.main === module) {
  sendEmail()
}
